//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokageVulnExample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TokageVulnExample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html dir=&quot;ltr&quot; hascustombackground=&quot;false&quot; bookmarkbarattached=&quot;false&quot; lang=&quot;en&quot; class=&quot;md&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Simple HTML Form&lt;/title&gt;
        ///        &lt;style&gt;
        ///            html {
        ///                height: 100%;
        ///            }
        ///            body {
        ///                background-color: lightgray;
        ///                display: grid;
        ///                grid-template-columns: repeat(3, 1fr);
        ///                grid-template-rows: repeat(4, 1fr);
        ///                min-height: 100%;
        ///            }
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string attackerPage {
            get {
                return ResourceManager.GetString("attackerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html dir=&quot;ltr&quot; hascustombackground=&quot;false&quot; bookmarkbarattached=&quot;false&quot; lang=&quot;en&quot; class=&quot;md&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Simple HTML Form&lt;/title&gt;
        ///        &lt;style&gt;
        ///            html {
        ///                height: 100%;
        ///            }
        ///            body {
        ///                background-color: lightgray;
        ///                display: grid;
        ///                grid-template-columns: 1fr 2fr 1fr;
        ///                grid-template-rows: repeat(4, 1fr);
        ///                min-height: 100%;
        ///            }
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string forgotPage {
            get {
                return ResourceManager.GetString("forgotPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html dir=&quot;ltr&quot; hascustombackground=&quot;false&quot; bookmarkbarattached=&quot;false&quot; lang=&quot;en&quot; class=&quot;md&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Simple HTML Form&lt;/title&gt;
        ///        &lt;style&gt;
        ///            html {
        ///                height: 100%;
        ///            }
        ///            body {
        ///                background-color: lightgray;
        ///                display: grid;
        ///                grid-template-columns: repeat(3, 1fr);
        ///                grid-template-rows: repeat(4, 1fr);
        ///                min-height: 100%;
        ///            }
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string loginPage {
            get {
                return ResourceManager.GetString("loginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html dir=&quot;ltr&quot; hascustombackground=&quot;false&quot; bookmarkbarattached=&quot;false&quot; lang=&quot;en&quot; class=&quot;md&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Simple HTML Form&lt;/title&gt;
        ///        &lt;style&gt;
        ///            html {
        ///                height: 100%;
        ///            }
        ///            body {
        ///                background-color: lightgray;
        ///                display: grid;
        ///                grid-template-columns: 1fr 2fr 1fr;
        ///                grid-template-rows: repeat(4, 1fr);
        ///                min-height: 100%;
        ///            }
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string resetPage {
            get {
                return ResourceManager.GetString("resetPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html dir=&quot;ltr&quot; hascustombackground=&quot;false&quot; bookmarkbarattached=&quot;false&quot; lang=&quot;en&quot; class=&quot;md&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Simple HTML Form&lt;/title&gt;
        ///        &lt;style&gt;
        ///            html {
        ///                height: 100%;
        ///            }
        ///            body {
        ///                background-color: lightgray;
        ///                display: grid;
        ///                grid-template-columns: repeat(3, 1fr);
        ///                grid-template-rows: repeat(4, 1fr);
        ///                min-height: 100%;
        ///            }
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string targetPage {
            get {
                return ResourceManager.GetString("targetPage", resourceCulture);
            }
        }
    }
}
